name: Build

on:
  create:
    tags: [v*]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 13
          registry-url: https://npm.pkg.github.com
          scope: "@kydronepilot"

      - name: Install dependencies
        run: brew install inkscape imagemagick

      - name: Install NPM packages
        run: npm ci

      - name: Build icons
        run: npx gulp build

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
